global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    podMonitor:
      enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: jobber

jobs:
  enabled: true
  replicas: 1
  image: 'devcsalvia/jobber-jobs:latest'
  port: 3001

executor:
  enabled: true
  replicas: 1
  image: 'devcsalvia/jobber-executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: 'devcsalvia/jobber-auth:latest'
  port:
    http: 3000
    grpc: 5000
  jwt:
    secret: 3UVY2uEmkSrhlvgsytw6VyJePKqIevfI
    expirationMs: 3600000

